---
apiVersion: app/v1
kind: Deployment
metadata: 
  name: node-deploy
  #namespace: kube-system
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: sample-node
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: node
      labels:
        app: sample-node
    spec:
      containers:
        - name: node-deploy-pod 
          image: 935549327939.dkr.ecr.ap-south-2.amazonaws.com/node:latest       
          ports:
            - containerPort: 3005
              protocol: TCP  
