name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag node:${NODE_ENV}-${GITHUB_RUN_ID}
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push Docker image
      run: |
        IMAGE_URI=935549327939.dkr.ecr.ap-south-2.amazonaws.com/node:${NODE_ENV}-${GITHUB_RUN_ID},latest
        docker tag node:${NODE_ENV}-${GITHUB_RUN_ID}  $IMAGE_URI 
        docker push $IMAGE_URI

  deploy:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Update kubeconfig
      run: |
          aws eks update-kubeconfig --region ap-south-2 --name eks-node
    - name: Deploy to EKS
      run: |
          kubectl apply -f node-deploy.yaml
          kubectl apply -f node-svc.yaml

    
