name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: node-runner

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag node:${GITHUB_RUN_ID}
  deploy:

    runs-on: node-runner

    steps:
    - uses: actions/checkout@v4
    - name: deploy
      run: docker container run -d -P --name container1 node:${GITHUB_RUN_ID}

    
