name: sample-node-pipeline
on:
  push:
    branches:
      - master
env:
  ENV: Dev	      
jobs:
  build:
    name: this is build job
    runs-on: [self-hosted, linux, x64 ] 
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: building docker image
        run: |
          docker image build -t node:${{ env.ENV }}-${ GITHUB_RUN_NUMBER } .
