name: sample-node-pipeline
on:
  push:
    branches:
      - master
env:
  ENV: Dev	  
jobs:
  checkout:
    runs-on: aws
    steps:
      - name: checkout
        uses: actions/checkout@v4
        
  build:
    runs-on: self-hosted
    steps:
      - name: build docker image
        run: |
	  docker build -t node:${{ env.ENV }}-${GITHUB_RUN_NUMBER} --file=Dockerfile       
