name: sample-node-pipeline
on:
  push:
    branches:
      - master
env:
  ENV: Dev
jobs:
  checkout:
    runs-on: aws
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          HOST_URL: ${{ secrets.HOST_URL }}
