name: sample-node-pipeline
on:
  push:
    branches:
      - master
env:
  ENV: Dev
jobs:
  checkout:
    runs-on: aws
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  
      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@master
        with:
          host: ${{ secrets.HOST_URL }}
          login: ${{ secrets.SONAR_TOKEN }}
