name: sample-node-pipeline
on:
  push:
    branches:
      - master
env:
  ENV: Dev
  IMAGE_URI: 935549327939.dkr.ecr.ap-south-2.amazonaws.com/node:${{vars.NODE_ENV}}-${GITHUB_RUN_NUMBER}
jobs:
  build:
    name: this is build job
    runs-on: node-runner
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: building docker image
        run: |
          docker image build -t node:${{ env.ENV }}-${GITHUB_RUN_NUMBER} .
      - name: log into ecr
        uses: aws-actions/aws-ecr-login@v1
      - name: tagging and push 
        run: |
          docker tag node:${{ env.ENV }}-${GITHUB_RUN_NUMBER} ${{ env.IMAGE_URI	}} 
          docker push ${{ env.IMAGE_URI }}
