name: sample-node-pipeline
on:
  push:
    branches:
      - master
env:
  ENV: Dev	  
jobs:
  checkout:
    runs-on: aws
    steps:
      - name: checkout
        uses: actions/checkout@v4
  build:
    runs-on: aws
    steps:
      - name: build docker image
        run: docker image build -t node:${{ env.ENV }}-${GITHUB_RUN_NUMBER} .
